[build-system]
requires = [
    "setuptools>=61.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "llm_eval"
description = "Fireworks.ai Large Language Model Eval Suite"
readme = "README.md"
requires-python = ">=3.7"
authors = [
  { name="Fireworks AI", email="info@fireworks.ai" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "tqdm",
    "httpx",
    "jinja2",
    "numpy",
    "tabulate",
    "datasets",
    "transformers",
    "torch",
]
license = {file = "LICENSE"}
version = "0.0.1"

[project.urls]
"Homepage" = "https://fireworks.ai"

# Using tool.setuptools.packages.find automatically supports namespaced packages
[tool.setuptools.packages.find]
include = ["llm_eval", "llm_eval.*"]

[tool.setuptools.package-data]
"*" = ["*.jsonl", "*.jinja"]

[tool.black]
target-version = ['py36']
exclude = '.*\.ipynb'
# 'extend-exclude' excludes files or directories in addition to the defaults
# note: it's duplicated in .vscode/settings.json because Black extension has trouble finding pyproject.toml
extend-exclude = '''
(
  | .*_pb2.*.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
py_version = 36
include_trailing_comma = "true"
line_length = 80
multi_line_output = 3
